### ISSUE TITLE
Refactoring for "Transformation page"

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/datagraft#16]
Make look and feel similar to "Data page". Remove the label for the transformation description. Remove the type of transformation (not necessary for normal users). Add information to owner of transformation. Add keywords for transformations – to implement in Grafterizer. Add date of creation of the transformation. Add possibility to fork or delete transformation (if current user is owner). Change label for executing transformation: "Continue" -> "Publish data page". If not logged in, as soon as a user tries to execute/fork public transformations, prompt them to log in.

**Comment by momchill** [comment]
implemented
