### ISSUE TITLE
Modify description field in data pages

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/datagraft#23]
Typing in the multi-line description field looks strange with the current implementation that uses the same "look" as an input field

**Comment by nvnikolov** [comment]
![d25f72c78641364220e395ec230dad1e03012fb4bc305fa7f8 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/8124245/9872761/c35a5810-5b9b-11e5-970d-5d07ce143436.jpg)

**Comment by momchill** [comment]
fixed

**Comment by nvnikolov** [comment]
Data page opened from "Explore":
![image](https://cloud.githubusercontent.com/assets/8124245/9958526/2da02a9e-5e0b-11e5-86c1-5110ca640b8f.png)
