### ISSUE TITLE
Bugs in widget dialog when editing a data page 

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/datagraft#35]
- Title, description and summary do not appear in the preview (not sure about the data-driven portal)
  ![image](https://cloud.githubusercontent.com/assets/8124245/9444954/de5bc4e6-4a89-11e5-88f7-fc4ba0b5595c.png)
- If the query has a lot of parameters, the result sometimes is larger than the screen size:
  ![image](https://cloud.githubusercontent.com/assets/8124245/9444514/8f853e9e-4a87-11e5-9cee-808508885af2.png)
- some widgets display too small for the dialog:
  ![image](https://cloud.githubusercontent.com/assets/8124245/9444556/cd2b970c-4a87-11e5-8da8-035d24b4d534.png)
- There is a strange light stripe in the middle of the screen when the dialog is open:
  ![image](https://cloud.githubusercontent.com/assets/8124245/9444588/f96a6a0a-4a87-11e5-9f31-8d2c0ce31a20.png)
- Query doesn't change when changing the widget type if you have edited/clicked in the query specification box
- Preview doesn't change when the input query has mistakes

**Comment by momchill** [comment]
Preview option is 'query results preview'. it is not intended to preview entire portal.
Other issues are fixed.
