### ISSUE TITLE
Prompted to sign in despite username being displayed

### ISSUE THREAD

**Issue by bcouston** [dapaas/datagraft#42]
On the homepage, my username was in the top right corner, but on clicking it, I was taken to the sign in page. Seems like either I should not be navigated to this page or I should not see my username on the homepage.
![screen shot 2015-09-04 at 11 51 03](https://cloud.githubusercontent.com/assets/9949074/9682115/9a3816aa-52fb-11e5-9bef-06a8e3874fb2.png)

(BUG)

**Comment by bcouston** [comment]
This occurred even if I had signed out, potential security risk as it displays the username of the last logged in user.

**Comment by fungiboletus** [comment]
Yes, we don't have the information about whether the user is connected/disconnected from this view. We only have the login name from a cookie expiring after 25 years

@yordankailieva Is it possible to remove the dapaas_user_login_ever when the user logouts? Or can you have a new cookie saying whether the user is connected or disconnected? We can't use the JSESSIONID cookie from JavaScript.
