### ISSUE TITLE
Username can change to an id when logging in with Facebook

### ISSUE THREAD

**Issue by bcouston** [dapaas/datagraft#48]
After some navigating after logging in with a fb account, the username in the top right corner changed to an id (see image).
![screen shot 2015-09-04 at 15 20 47](https://cloud.githubusercontent.com/assets/9949074/9686012/8053888c-5319-11e5-8b44-c580370e75bf.png)

(BUG)

**Comment by fungiboletus** [comment]
It looks like the dapaas_user_login_ever doesn't alway contain an username. We can maybe hide it when it's a number.

**Comment by momchill** [comment]
dapaas_user_login_ever can be user_id in case of login with social account. We can introduce new cookie for user_name that will be more useful for home page.

**Comment by fungiboletus** [comment]
That would be perfect. If this cookie is deleted when the user logs out, it can also be used for the issue #42.

**Comment by yordankailieva** [comment]
I implement new cookie with name : "user_name" the value is name of login user ( if the user login with FB, G+ or Twitter value is name of relevant account ). When user logout remove the cookie. Cookie max age is 2h.
