### ISSUE TITLE
API error after every attempt at creating a new data transformation

### ISSUE THREAD

**Issue by bcouston** [dapaas/datagraft#52]
This only occurred in an older version of Chrome, specifically 44.0.2403.125.

After causing #51, I attempted to create a new data transformation on another file. However on doing this, I received an API error (see image). This error repeatedly occurred with every data set. It only ceased when I tried to replicate in Incognitio Mode. After one attempt at replicate the issue, it happened again and subsequently.

![screen shot 2015-09-04 at 15 08 46](https://cloud.githubusercontent.com/assets/9949074/9688589/00c5ae10-5328-11e5-9feb-633afcce86ed.png)

This leads me to believe that this error was browser-based, concerning cookies or local/session storage. After updating I could not replicate the issue, however it is something to be made aware of as it essentially takes away a large chunk of the functionality.

(BUG)

**Comment by fungiboletus** [comment]
Hi,
I should have fixed this error this morning. When did that happen? It could be a outdated scripts files in your browser cache or the Amazon CDN.

**Comment by fungiboletus** [comment]
I can't reproduce the error. Please reopen whether it happens again.
