### ISSUE TITLE
Enhancement - breadcrumbs unintuitive

### ISSUE THREAD

**Issue by quadrophobiac** [dapaas/datagraft#54]
As a User,
When I navigate to dashboard the breadcrumbs display as follows:
![screen shot 2015-09-07 at 16 45 24](https://cloud.githubusercontent.com/assets/1039017/9732853/e0448b44-561e-11e5-9af1-ccc8563f92f4.png)

However when I navigate to `Explore`, `dashboard` is only available by the header menu
This adds up to a disorienting navigation experience

**Comment by momchill** [comment]
Breadcrumb removed
