### ISSUE TITLE
Hover text to describe 'portal' identifier in 'Explore'

### ISSUE THREAD

**Issue by quadrophobiac** [dapaas/datagraft#55]
As a user navigating to the `explore public datapages/transformations` hub
If the list of datapages is populated with published pages which do not satisfy criteria to gain a 'portal' icon - 

![screen shot 2015-09-08 at 11 48 31](https://cloud.githubusercontent.com/assets/1039017/9732926/8fe3c894-561f-11e5-93a5-14fff3023aa0.png)

Then the portal filter option in the header  
![screen shot 2015-09-08 at 11 47 34](https://cloud.githubusercontent.com/assets/1039017/9732915/6e469748-561f-11e5-90ea-d23cd15e7d7b.png)
communicates no useful information as to what sort of filtering it affords

**Comment by momchill** [comment]
Icon removed
