### ISSUE TITLE
Session data gets mixed up

### ISSUE THREAD

**Issue by dinans** [dapaas/datagraft#66]
If I open several different datapages in different tabs, session data gets mixed and all tabs contain information for the last opened datapage

Tabs show different endpoints originally:
![issue1](https://cloud.githubusercontent.com/assets/8913146/9938719/f55db664-5d66-11e5-9c28-661ad3928140.png)

After performing some simple query, both point to the same endpoint:
![issue2](https://cloud.githubusercontent.com/assets/8913146/9938737/0b5229aa-5d67-11e5-81f7-4b550c8ce85f.png)

**Comment by momchill** [comment]
Tabs share the same session, so when you open new tab it's data overwrite previous data in session. We have applyed fix that will prevent data coruption due to session data mix up, but we cannot support managing 2 datapages in one session at the same time.
