### ISSUE TITLE
Forking of public transformations fails in "Dashboard" and "Explore"

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/datagraft#67]
Error in Google Chrome console reads: 

POST https://datagraft.net/BaseGateway/forkTransformation.json 500 (Internal Server Error)
Uncaught SyntaxError: Unexpected token <

**Comment by momchill** [comment]
cannot reproduce. may be cache problem?

**Comment by nvnikolov** [comment]
Indeed it was a cache issue - thanks! :+1:
