### ISSUE TITLE
Refactoring "Publish" page

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/datagraft#9]
Make it possible to create CSV-only data pages. On downloading/uploading files restrict to files up to a size of 10MB. Remove green arrow to make it more consistent with the other file upload controls. Restrict only to CSV or RDF data, also add text that clarifies that - e.g. add text "(CSV or any RDF format)". When file is dropped – display only the file; make sure it doesn't seem that you can upload more than 1 file as it is a little misleading now

**Comment by yordankailieva** [comment]
Implement new improvements.
